# Generated by Django 2.1.7 on 2019-03-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDelivery', '0002_auto_20190317_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=3)),
                ('pid', models.CharField(max_length=3)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8)),
                ('order_id', models.CharField(max_length=3)),
                ('delivery_address', models.CharField(max_length=255)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('pid', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='py_user_details',
            new_name='user_details',
        ),
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('username', 'order_id')},
        ),
        migrations.AlterUniqueTogether(
            name='order_details',
            unique_together={('order_id', 'pid')},
        ),
    ]
