# Generated by Django 2.1.7 on 2019-04-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDelivery', '0003_auto_20190317_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='gender',
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(max_length=32),
        ),
    ]
