# Generated by Django 2.1.7 on 2019-04-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDelivery', '0005_auto_20190405_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='image',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
