# Generated by Django 2.1.7 on 2019-04-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDelivery', '0007_auto_20190406_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='dob',
        ),
        migrations.AlterField(
            model_name='user_details',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
